#!/usr/env bash

watchmedo shell-command \
    --patterns="*" \
    --ignore-directories \
    --recursive \
    --command='cd /var/www/site; git add --all; git commit -am "update version"; git push origin master -f;' \
    /var/www/site/
