#!/usr/bin/env bash

while true; do
	if [ $(git status | grep "nada a submeter")  ]; then
	    sleep 2m;
	else
	    cd /var/www/site;
	    git add --all;
	    git commit -am "update version";
	    git push origin master -f;
	fi
done
