#!/usr/bin/env bash

cd /var/www/site;

git config --global user.email "site@kappius.com.br";

git config --global user.name "Site Kappius";

while true; do
	if [[ $(git status | grep "nada a submeter")  ]]; then
	    sleep 2m;
	else
	    git add --all;
	    git commit -am "update version";
	    git push origin master -f;
	fi
done
